---
- name: Install Catalogue Component
  hosts: catalogue
  become: yes
  tasks:
  - name: Setup NodeJS repos
    ansible.builtin.shell: "curl -sL https://rpm.nodesource.com/setup_lts.x | bash"
  - name: Install NodeJS
    ansible.builtin.yum: 
      name: nodejs
      state: installed
  - name: Checking roboshop user exist or not
    ansible.builtin.command: id roboshop
    register: user_status
    ignore_errors: yes
  - name: Creating roboshop User if not exist
    when: user_status.rc != 0
    ansible.builtin.user: 
      name: roboshop
  - name: Checking Directory exit or not
    ansible.builtin.stat:
      path: /app
    register: Dir_Status
    ignore_errors: yes
  - name: Print The Dir Statistics
    ansible.builtin.debug:
      msg: "Dir_Statistics : {{Dir_Status}}"
  - name: Creating /app Directory
    when: Dir_Status.rc != 0
    ansible.builtin.command: mkdir /app
  

