---
- name: Test Play
  hosts: web
  become: true
  tasks:
  - name: Process Check
    ignore_errors: yes
    ansible.builtin.shell: ps -ef | grep {{item}} | grep -v grep
    loop:
    - nginx
    - apache
    register: ps_out

  - name: Print OutPut
    ansible.builtin.command: echo "{{ps_out}}"

