- name: Checking roboshop user exist or not
  ansible.builtin.command: id roboshop
  register: user_status
  ignore_errors: yes

- name: User Status
  ansible.builtin.debug:
    msg: "User Status : {{user_status}}"

- name: Creating roboshop User if not exist
  when: user_status.rc != 0
  ansible.builtin.user: 
    name: roboshop

- name: Checking Directory exit or not
  ansible.builtin.stat:
    path: /app
  register: Dir_Status
  ignore_errors: yes

- name: Print The Dir Statistics
  ansible.builtin.debug:
    msg: "Dir_Statistics : {{Dir_Status}}"

- name: Creating /app Directory
  when: Dir_Status.stat.exists == False
  ansible.builtin.file:
    path: /app
    state: directory

- name: Download the application code to /app directory
  ansible.builtin.get_url:
    url: https://roboshop-builds.s3.amazonaws.com/{{component}}.zip
    dest: /tmp/{{component}}.zip
    mode: '0777'

- name: Extracting /tmp/catalogue.zip in to /app
  ansible.builtin.unarchive:
    src: /tmp/{{component}}.zip
    dest: /app
    remote_src: yes
