- name: Checking Directory exit or not
  ansible.builtin.stat:
    path: /app
  register: Dir_Status
  ignore_errors: yes

- name: Print The Dir Statistics
  ansible.builtin.debug:
    msg: "Dir_Statistics : {{Dir_Status}}"

- name: Creating /app Directory
  when: Dir_Status.stat.exists == False
  ansible.builtin.file:
    path: /app
    state: directory