- name: Checking roboshop user exist or not
  ansible.builtin.command: id roboshop
  register: user_status
  ignore_errors: yes

- name: Print The User Status
  ansible.builtin.debug:
    msg: "User Status : {{user_status}}"

- name: Creating roboshop User if not exist
  when: user_status.rc != 0
  ansible.builtin.user: 
    name: roboshop