- name: Import common role
  ansible.builtin.import_role:
    name: common
    tasks_from: nodejs

- name: Install Apllication Code
  ansible.builtin.import_role:
    name: common
    tasks_from: app-setup

- name: Install Dependencies
  ansible.builtin.command: npm install
  args:
    chdir: /app

- name: Install Apllication Code
  ansible.builtin.import_role:
    name: common
    tasks_from: systemd-setup

- name: Install Apllication Code
  ansible.builtin.import_role:
    name: common
    tasks_from: mongodb-shema

- name: Install Apllication Code
  ansible.builtin.import_role:
    name: common
    tasks_from: service-start


   