- name: Import common role
  ansible.builtin.import_role:
    name: common
    tasks_from: nodejs

- name: Install Apllication Code
  ansible.builtin.import_role:
    name: common
    tasks_from: app-setup